server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

ljh:
 key: qwer123
 
file:
 path: C:\스프링\blog\src\main\resources/static/image/

spring:
  devtools:
    restart:
      enabled: true
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB  
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springstudy?serverTimezone=Asia/Seoul
    username: root
    password: ljh4284416

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
      format_sql: true
      

      
 



